# Generated by Django 6.0.2 on 2026-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="section",
            field=models.CharField(
                choices=[
                    ("bhajan", "Bhajan"),
                    ("chorus", "Chorus"),
                    ("baal_chorus", "Baal Chorus"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="slot",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
